"""empty message

Revision ID: 1b25723059d6
Revises: e25fdf3278bf
Create Date: 2019-08-23 12:49:57.512115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b25723059d6'
down_revision = 'e25fdf3278bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('RTBH', 'community_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('RTBH', 'rstate_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('RTBH', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('RTBH', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('RTBH', 'rstate_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('RTBH', 'community_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
