"""empty message

Revision ID: 2bd0e800ab1c
Revises: 4fa1bacabe4d
Create Date: 2022-04-29 14:35:23.856715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd0e800ab1c'
down_revision = '4fa1bacabe4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('as_path',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(length=120), nullable=True),
    sa.Column('as_path', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prefix')
    )
    op.add_column('community', sa.Column('as_path', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community', 'as_path')
    op.drop_table('as_path')
    # ### end Alembic commands ###
