"""empty message

Revision ID: 3003649af016
Revises: 701711e8c4f4
Create Date: 2019-08-26 08:43:04.219577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3003649af016'
down_revision = '701711e8c4f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('community', 'comm',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=120),
               type_=sa.String(length=2047),
               existing_nullable=True)
    op.alter_column('community', 'description',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=260),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('community', 'extcomm',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=120),
               type_=sa.String(length=2047),
               existing_nullable=True)
    op.alter_column('community', 'larcomm',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=120),
               type_=sa.String(length=2047),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('community', 'larcomm',
               existing_type=sa.String(length=2047),
               type_=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=120),
               existing_nullable=True)
    op.alter_column('community', 'extcomm',
               existing_type=sa.String(length=2047),
               type_=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=120),
               existing_nullable=True)
    op.alter_column('community', 'description',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=260),
               existing_nullable=True)
    op.alter_column('community', 'comm',
               existing_type=sa.String(length=2047),
               type_=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=120),
               existing_nullable=True)
    # ### end Alembic commands ###
