"""empty message

Revision ID: 4fa1bacabe4d
Revises: 5945c1418f0f
Create Date: 2022-04-20 12:30:48.123941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa1bacabe4d'
down_revision = '5945c1418f0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flowspec4', sa.Column('fragment', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flowspec4', 'fragment')
    # ### end Alembic commands ###
