"""add rule counters to organization

Revision ID: 58ac38ced7f6
Revises: 7719224c9f1f
Create Date: 2024-10-15 16:53:48.222167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58ac38ced7f6'
down_revision = '7719224c9f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ipv4count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ipv6count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rtbhcount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('rtbhcount')
        batch_op.drop_column('ipv6count')
        batch_op.drop_column('ipv4count')

    # ### end Alembic commands ###
