"""empty message

Revision ID: 5945c1418f0f
Revises: 3003649af016
Create Date: 2021-03-09 12:57:56.549338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5945c1418f0f'
down_revision = '3003649af016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('author', sa.String(length=1000), nullable=True))
    op.alter_column('log', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('log_ibfk_1', 'log', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('log_ibfk_1', 'log', 'user', ['user_id'], ['id'])
    op.alter_column('log', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('log', 'author')
    # ### end Alembic commands ###
