"""empty message

Revision ID: 701711e8c4f4
Revises: 1b25723059d6
Create Date: 2019-08-23 13:05:45.140334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '701711e8c4f4'
down_revision = '1b25723059d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('action', 'role_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text(u"'0'"))
    op.alter_column('api_key', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('community', 'role_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('flowspec4', 'action_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('flowspec4', 'rstate_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('flowspec4', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('flowspec6', 'action_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('flowspec6', 'rstate_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('flowspec6', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('log', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('flowspec6', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('flowspec6', 'rstate_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('flowspec6', 'action_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('flowspec4', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('flowspec4', 'rstate_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('flowspec4', 'action_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('community', 'role_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('api_key', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('action', 'role_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text(u"'0'"))
    # ### end Alembic commands ###
