"""empty message

Revision ID: 76856add9483
Revises: b3efc4d93b12
Create Date: 2019-01-28 10:22:17.904055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76856add9483'
down_revision = 'b3efc4d93b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('command', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=260), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('command'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('community')
    # ### end Alembic commands ###
