"""empty message

Revision ID: 7a816ca986b3
Revises: 76856add9483
Create Date: 2019-01-28 11:59:08.217024

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a816ca986b3'
down_revision = '76856add9483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RTBH', sa.Column('community_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'RTBH', 'community', ['community_id'], ['id'])
    op.drop_column('RTBH', 'community')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RTBH', sa.Column('community', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'RTBH', type_='foreignkey')
    op.drop_column('RTBH', 'community_id')
    # ### end Alembic commands ###
