"""organization in apikey and machineapikey models

Revision ID: ae99a66ed9f8
Revises: e25b385bae2c
Create Date: 2024-10-18 11:35:18.402633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae99a66ed9f8'
down_revision = 'e25b385bae2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'organization', ['org_id'], ['id'])

    with op.batch_alter_table('machine_api_key', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'organization', ['org_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine_api_key', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('org_id')

    # ### end Alembic commands ###
