"""empty message

Revision ID: e25fdf3278bf
Revises: 7a816ca986b3
Create Date: 2019-08-22 13:39:34.983566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e25fdf3278bf'
down_revision = '7a816ca986b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community', sa.Column('comm', sa.String(length=120), nullable=True))
    op.add_column('community', sa.Column('extcomm', sa.String(length=120), nullable=True))
    op.add_column('community', sa.Column('larcomm', sa.String(length=120), nullable=True))
    op.drop_index('command', table_name='community')
    op.drop_column('community', 'command')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community', sa.Column('command', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=120), nullable=True))
    op.create_index('command', 'community', ['command'], unique=True)
    op.drop_column('community', 'larcomm')
    op.drop_column('community', 'extcomm')
    op.drop_column('community', 'comm')
    # ### end Alembic commands ###
